import type {
  AgentStatus,
  ListReportRunsParams,
  ListAgentsParams,
  ListAlertsParams,
  ListAssetsParams,
  ListCredentialsParams,
  ListLogsParams,
  ListPeopleParams,
  ListSnmpDevicesParams,
  LogSummaryParams,
  ListTicketsParams,
  Severity,
} from './types';

export const queryKeys = {
  clients: ['clients'] as const,
  deployments: ['deployments'] as const,
  agents: ['agents'] as const,
  agentLists: ['agents', 'list'] as const,
  agentList: (params: ListAgentsParams) => ['agents', 'list', params] as const,
  agentDetails: ['agents', 'detail'] as const,
  agentDetail: (id: number) => ['agents', 'detail', id] as const,
  agentCounts: ['agents', 'count'] as const,
  agentCount: (status: AgentStatus | 'all') => ['agents', 'count', status] as const,
  // Fora de ['agents']: consultas ao vivo nao devem ser refeitas a cada evento agentsChanged.
  agentHistory: (id: number) => ['agent-live', id, 'history'] as const,
  agentProcesses: (id: number) => ['agent-live', id, 'processes'] as const,
  agentServices: (id: number) => ['agent-live', id, 'services'] as const,
  agentEventLog: (id: number, log: string, days: number) => ['agent-live', id, 'eventlog', log, days] as const,
  agentRegistry: (id: number, path: string) => ['agent-live', id, 'registry', path] as const,
  scripts: ['scripts'] as const,
  script: (id: number) => ['scripts', 'detail', id] as const,
  snippets: ['snippets'] as const,
  keystore: ['keystore'] as const,
  urlActions: ['url-actions'] as const,
  globalSettings: ['global-settings'] as const,
  // Monitoramento: fora de ['agents'] pelo mesmo motivo das consultas ao vivo.
  agentMonitoring: (id: number) => ['agent-monitoring', id] as const,
  agentChecks: (id: number) => ['agent-monitoring', id, 'checks'] as const,
  checkHistory: (checkId: number, agentId: number, hours: number) => ['agent-monitoring', agentId, 'check-history', checkId, hours] as const,
  agentTasks: (id: number) => ['agent-monitoring', id, 'tasks'] as const,
  agentPolicies: (id: number) => ['agent-monitoring', id, 'policies'] as const,
  agentUpdates: (id: number) => ['agent-monitoring', id, 'updates'] as const,
  agentPatchPolicy: (id: number) => ['agent-monitoring', id, 'patch-policy'] as const,
  agentSoftware: (id: number) => ['agent-monitoring', id, 'software'] as const,
  agentPendingActions: (id: number) => ['agent-monitoring', id, 'pending-actions'] as const,
  softwareCatalog: (source: string, q: string) => ['software-catalog', source, q] as const,
  policies: ['policies'] as const,
  policy: (id: number) => ['policies', 'detail', id] as const,
  policyAssignments: ['policies', 'assignments'] as const,
  alerts: ['alerts'] as const,
  alertList: (params: ListAlertsParams) => ['alerts', 'list', params] as const,
  alertSeverityCount: (severity: Severity) => ['alerts', 'count', severity] as const,
  /** Contador do menu: atualizado pelo evento alertsChanged, sem nova requisicao. */
  activeAlertCount: ['alert-active-count'] as const,
  alertTemplates: ['alert-templates'] as const,
  alertTemplateAssignments: ['alert-templates', 'assignments'] as const,
  tickets: ['tickets'] as const,
  ticketLists: ['tickets', 'list'] as const,
  ticketList: (params: ListTicketsParams) => ['tickets', 'list', params] as const,
  ticketSummary: ['tickets', 'summary'] as const,
  agentTicketLists: ['tickets', 'agent'] as const,
  agentTickets: (agentId: number) => ['tickets', 'agent', agentId] as const,
  /** Prefixo do detalhe: inclui mensagens, anexos e apontamentos do chamado. */
  ticketDetail: (id: number) => ['tickets', 'detail', id] as const,
  ticketMessages: (id: number) => ['tickets', 'detail', id, 'messages'] as const,
  ticketAttachments: (id: number) => ['tickets', 'detail', id, 'attachments'] as const,
  ticketTime: (id: number) => ['tickets', 'detail', id, 'time'] as const,
  ticketAssignees: ['ticket-assignees'] as const,
  ticketQueues: ['ticket-queues'] as const,
  ticketSla: ['ticket-sla'] as const,
  ticketIncidentSettings: ['ticket-incident-settings'] as const,
  assets: ['assets'] as const,
  assetLists: ['assets', 'list'] as const,
  assetList: (params: ListAssetsParams) => ['assets', 'list', params] as const,
  assetSheets: ['assets', 'sheet'] as const,
  assetSheet: (id: number) => ['assets', 'sheet', id] as const,
  people: ['people'] as const,
  peopleLists: ['people', 'list'] as const,
  peopleList: (params: ListPeopleParams) => ['people', 'list', params] as const,
  person: (id: number) => ['people', 'detail', id] as const,
  networks: ['networks'] as const,
  networkList: (clientId: number | undefined) => ['networks', 'list', clientId ?? null] as const,
  network: (id: number) => ['networks', 'detail', id] as const,
  diagrams: ['diagrams'] as const,
  diagramLists: ['diagrams', 'list'] as const,
  diagramList: (clientId: number | undefined) => ['diagrams', 'list', clientId ?? null] as const,
  diagram: (id: number) => ['diagrams', 'detail', id] as const,
  credentials: ['credentials'] as const,
  credentialList: (params: ListCredentialsParams) => ['credentials', 'list', params] as const,
  docPages: ['doc-pages'] as const,
  docPageList: (clientId: number | undefined, search: string) => ['doc-pages', 'list', clientId ?? null, search] as const,
  docPage: (id: number) => ['doc-pages', 'detail', id] as const,
  // Cybereyes Care: fora de ['agents'] para nao pedir o catalogo ao agente a cada agentsChanged.
  careCatalog: (agentId: number) => ['agent-live', agentId, 'care-catalog'] as const,
  careRunLists: ['care', 'runs'] as const,
  careRuns: (agentId: number, page: number) => ['care', 'runs', agentId, page] as const,
  careRun: (runId: string) => ['care', 'run', runId] as const,
  agentHealth: (agentId: number) => ['agent-health', agentId] as const,
  careSelfService: ['care-self-service'] as const,
  logs: ['logs'] as const,
  logLists: ['logs', 'list'] as const,
  logList: (params: Omit<ListLogsParams, 'before'>) => ['logs', 'list', params] as const,
  logSummary: (params: LogSummaryParams) => ['logs', 'summary', params] as const,
  logSettings: ['log-settings'] as const,
  logAlertRules: ['log-alert-rules'] as const,
  snmp: ['snmp'] as const,
  snmpDeviceLists: ['snmp', 'devices'] as const,
  snmpDevices: (params: ListSnmpDevicesParams) => ['snmp', 'devices', params] as const,
  snmpDevice: (id: number) => ['snmp', 'device', id] as const,
  snmpMetrics: (id: number, metric: string, hours: number) => ['snmp', 'device', id, 'metrics', metric, hours] as const,
  snmpCollectors: ['snmp', 'collectors'] as const,
  reportTypes: ['reports', 'types'] as const,
  reportRuns: ['reports', 'runs'] as const,
  reportRunList: (params: ListReportRunsParams) => ['reports', 'runs', params] as const,
  reportSchedules: ['reports', 'schedules'] as const,
  ssoLoginOptions: ['sso-login-options'] as const,
  ssoProviders: ['sso', 'providers'] as const,
  ssoSettings: ['sso', 'settings'] as const,
  roleOptions: ['roles', 'options'] as const,
  userDetail: (id: string) => ['users', 'detail', id] as const,
};
